name: Workflow 1
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hi There"
      - name: Print bye
        run: echo "Later nitz"
