name: exercise-one
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run tests
        run: npm run test      
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:      
      - name: build
        run: npm run build
      - name: deploy
        run: echo "deploying...need to hook in AwS"
name: Handle issues
on: issues
jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: echo "${{ toJSON(github.event) }}"


    